SP18.PF.Web/Areas/Admin/Models/Shared/AddressProfile.cs
using AutoMapper;
using SP18.PF.Core.Features.Shared;

namespace SP18.PF.Web.Areas.Admin.Models.Shared
{
    public class AddressProfile : Profile
    {
        public AddressProfile()
        {
            CreateMap<Address, Address>();
        }
    }
}

SP18.PF.Web/Areas/Admin/Models/Shared/AddressValidator.cs
using FluentValidation;
using SP18.PF.Core.Features.Shared;

namespace SP18.PF.Web.Areas.Admin.Models.Shared
{
    public class AddressValidator : AbstractValidator<Address>
    {
        public AddressValidator()
        {
            RuleFor(x => x.AddressLine1)
                .NotEmpty()
                .Length(1, 64);
            RuleFor(x => x.AddressLine2)
                .Length(0, 64);
            RuleFor(x => x.City)
                .NotEmpty()
                .Length(1, 64);
            RuleFor(x => x.ZipCode)
                .NotEmpty()
                .Length(5);
            RuleFor(x => x.State)
                .NotEmpty()
                .Must(States.IsStateCode)
                .WithMessage("Invalid state, use the 2 letter state code. e.g. LA");
        }
    }
}

SP18.PF.Web/Areas/Admin/Models/Shared/CrudProfile.cs
using AutoMapper;

namespace SP18.PF.Web.Areas.Admin.Models.Shared
{
    public abstract class CrudProfile<TEntity, TListing, TCreate, TEdit> : Profile
        where TEntity : class
    {
        protected CrudProfile()
        {
            CreateMap<TEntity, TListing>();
            CreateMap<TEntity, TEdit>();
            CreateMap<TCreate, TEntity>();
            CreateMap<TEdit, TEntity>();
        }
    }
}

SP18.PF.Web/Areas/Admin/Controllers/EventsController.cs
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SP18.PF.Core.Features.Events;
using SP18.PF.Core.Features.Roles;
using SP18.PF.Core.Features.Tours;
using SP18.PF.Core.Features.Venues;
using SP18.PF.Web.Areas.Admin.Models.Events;
using SP18.PF.Web.Extensions;
using SP18.PF.Web.Services;

namespace SP18.PF.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RoleNames.Admin)]
    public class EventsController : CrudController<Event, EventListingViewModel, EventCreateViewModel, EventEditViewModel>
    {
        private readonly DbContext dbContext;

        public EventsController(CrudService<Event, EventListingViewModel, EventCreateViewModel, EventEditViewModel> crudService, DbContext dbContext) : base(crudService)
        {
            this.dbContext = dbContext;
        }
        
        protected override Expression<Func<Event, bool>> GetSelectSingle(string id)
        {
            var item = id.SafeParseInt();
            return x => x.Id == item;
        }

        protected override async Task<EventCreateViewModel> GetCreateViewModel(EventCreateViewModel vm)
        {
            var result = vm ?? new EventCreateViewModel();
            var tours = await dbContext.Set<Tour>().Select(x => new {x.Id, x.Name}).ToArrayAsync();
            result.TourSelectList = new SelectList(tours, nameof(Tour.Id), nameof(Tour.Name));
            var venues = await dbContext.Set<Venue>().Select(x => new { x.Id, x.Name }).ToArrayAsync();
            result.VenueSelectList = new SelectList(venues, nameof(Venue.Id), nameof(Venue.Name));
            return result;
        }
    }
}

SP18.PF.Web/Areas/Admin/Controllers/ToursController.cs
using System;
using System.Linq.Expressions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SP18.PF.Core.Features.Roles;
using SP18.PF.Core.Features.Tours;
using SP18.PF.Web.Areas.Admin.Models.Tours;
using SP18.PF.Web.Extensions;
using SP18.PF.Web.Services;

namespace SP18.PF.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RoleNames.Admin)]
    public class ToursController : CrudController<Tour, TourViewModel, TourViewModel, TourViewModel>
    {
        public ToursController(CrudService<Tour, TourViewModel, TourViewModel, TourViewModel> crudService) : base(crudService)
        {
        }

        protected override Expression<Func<Tour, bool>> GetSelectSingle(string id)
        {
            var item = id.SafeParseInt();
            return x => x.Id == item;
        }
    }
}

SP18.PF.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SP18.PF.Core.Features.Roles;
using SP18.PF.Core.Features.Users;
using SP18.PF.Web.Areas.Admin.Models.Users;
using SP18.PF.Web.Extensions;
using SP18.PF.Web.Services;

namespace SP18.PF.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RoleNames.Admin)]
    public class UsersController : CrudController<User, UserListViewModel, UserCreateViewModel, UserEditViewModel>
    {
        private readonly IValidator<UserCreateViewModel> createValidator;

        public UsersController(
            CrudService<User, UserListViewModel, UserCreateViewModel, UserEditViewModel> crudService,
            IValidator<UserCreateViewModel> createValidator)
            : base(crudService)
        {
            this.createValidator = createValidator;
        }

        [HttpGet, HttpPost]
        public async Task<IActionResult> VerifyEmail(string email)
        {
            var result = await createValidator.ValidateAsync(new UserCreateViewModel
            {
                Email = email
            });
            var errorMessage = result.Errors
                .Where(x => x.PropertyName == nameof(UserCreateViewModel.Email))
                .Select(x => x.ErrorMessage)
                .FirstOrDefault();
            if (string.IsNullOrWhiteSpace(errorMessage))
            {
                return Json(true);
            }

            return Json(errorMessage);
        }

        protected override Task<UserCreateViewModel> GetCreateViewModel(UserCreateViewModel vm)
        {
            return Task.FromResult(new UserCreateViewModel
            {
                Email = vm?.Email
            });
        }

        protected override Expression<Func<User, bool>> GetSelectSingle(string id)
        {
            var item = id.SafeParseInt();
            return x => x.Id == item;
        }
    }
}

SP18.PF.Web/Areas/Admin/Controllers/VenuesController.cs
using System;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SP18.PF.Core.Features.Roles;
using SP18.PF.Core.Features.Venues;
using SP18.PF.Web.Areas.Admin.Models.Venues;
using SP18.PF.Web.Extensions;
using SP18.PF.Web.Services;

namespace SP18.PF.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = RoleNames.Admin)]
    public class VenuesController : CrudController<Venue, VenueViewModel, VenueViewModel, VenueViewModel>
    {
        public VenuesController(CrudService<Venue, VenueViewModel, VenueViewModel, VenueViewModel> crudService) : base(crudService)
        {
        }

        protected override Task<VenueViewModel> GetCreateViewModel(VenueViewModel vm)
        {
            return Task.FromResult(vm ?? new VenueViewModel());
        }

        protected override Expression<Func<Venue, bool>> GetSelectSingle(string id)
        {
            var item = id.SafeParseInt();
            return x => x.Id == item;
        }
    }
}

SP18.PF.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wickets</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="~/lib/bootstrap-datetimepicker/bootstrap-datetimepicker.min.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="navbar-brand">Wickets</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                    <li><a asp-area="Admin" asp-controller="Tours" asp-action="Index">Tours</a></li>
                    <li><a asp-area="Admin" asp-controller="Venues" asp-action="Index">Venues</a></li>
                    <li><a asp-area="Admin" asp-controller="Events" asp-action="Index">Events</a></li>
                    <li><a asp-area="Admin" asp-controller="Tickets" asp-action="Index">Tickets</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-area="Admin" asp-controller="Account" asp-action="Logout">@User.Identity.Name - Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Wickets</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/moment/moment.js"></script>
        <script src="~/lib/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/lib/moment/moment.min.js"></script>
        <script src="~/lib/bootstrap-datetimepicker/bootstrap-datetimepicker.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SP18.PF.Web/Areas/Admin/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SP18.PF.Web</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/signin.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/signin.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">SP18.PF.Web</a>
            </div>
            <div class="navbar-collapse collapse">
            </div>
        </div>
    </nav>
    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>